--liquibase formatted sql

--changeset Badr04-dev:003-club-create
--comment: Create table CLUB

CREATE TABLE CLUB (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLUB_NAME VARCHAR(50) NOT NULL UNIQUE,
    FK_COACH_ID BIGINT NOT NULL,
    FK_STADIUM_NAME VARCHAR(100) NOT NULL,

    CONSTRAINT FK_CLUB_COACH
        FOREIGN KEY (FK_COACH_ID)
        REFERENCES COACH(ID),

    CONSTRAINT FK_CLUB_STADIUM
        FOREIGN KEY (FK_STADIUM_NAME)
        REFERENCES STADIUM(NAME)
);
