# Configuration PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/devdb
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Désactiver la génération automatique d'Hibernate (Liquibase s'en charge)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configuration Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

logging.level.org.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

